[package]
name = "ex3-shadowing"
version = "0.1.0"
edition = "2021"
author = "Hausdorff"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
